classDiagram
  class AuthRouter {
    +POST /auth/register
    +POST /auth/login
  }
  class ComplaintRouter {
    +POST /complaints
    +GET /complaints/my
    +POST /complaints/id/evidence
    +PATCH /complaints/id/verify
  }
  class OfficerRouter {
    +GET /officer/pool
    +POST /officer/id/accept
    +PATCH /officer/id/status
  }
  class CollectorRouter {
    +GET /collector/dashboard
  }
  class AdminRouter {
    +GET /admin/users
  }

  class AuthService {
    +register_user()
    +login_user()
  }
  class ComplaintService {
    +submit_complaint()
    +accept_complaint()
    +change_status()
    +upload_complaint_evidence()
    +verify_and_close()
  }
  class CollectorService {
    +get_dashboard()
  }
  class AdminService {
    +list_all_users()
  }

  class UserRepository {
    +get_user_by_email()
    +create_user()
  }
  class ComplaintRepository {
    +create_complaint()
    +assign_officer()
    +get_district_stats()
  }
  class StatusHistoryRepository {
    +add_status_entry()
  }
  class EvidenceRepository {
    +add_evidence()
  }
  class CloudStorage {
    +upload_image()
  }

  class UserModel
  class ComplaintModel
  class ComplaintStatusHistoryModel
  class ComplaintEvidenceModel

  AuthRouter --> AuthService
  ComplaintRouter --> ComplaintService
  OfficerRouter --> ComplaintService
  CollectorRouter --> CollectorService
  AdminRouter --> AdminService

  AuthService --> UserRepository
  ComplaintService --> ComplaintRepository
  ComplaintService --> StatusHistoryRepository
  ComplaintService --> EvidenceRepository
  ComplaintService --> CloudStorage
  CollectorService --> ComplaintRepository
  AdminService --> UserRepository

  UserRepository --> UserModel
  ComplaintRepository --> ComplaintModel
  StatusHistoryRepository --> ComplaintStatusHistoryModel
  EvidenceRepository --> ComplaintEvidenceModel