"""add officer id to complaints

Revision ID: 8f7a62bebec7
Revises: 2cc280710fcf
Create Date: 2026-08-10 14:08:36.348496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7a62bebec7'
down_revision: Union[str, Sequence[str], None] = '2cc280710fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'departments', ['department_id'], ['id'])
    op.add_column('complaints', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['officer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'officer_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'department_id')
    # ### end Alembic commands ###
